/**
 * Catálogo dos campos oficiais dos registros SPED (fase 2, requisitos 2 e 9).
 *
 * Este catálogo existe para conferência humana: a tela de inspeção mostra a
 * linha original do arquivo e, ao lado, cada campo com o **nome oficial** do
 * Guia Prático da obrigação. Se uma posição estiver errada, a conferência
 * revela imediatamente — que é exatamente o objetivo desta fase.
 *
 * As posições aqui declaradas são as mesmas lidas pelos handlers em
 * `efd-icms-ipi/layout.ts` e `efd-contribuicoes/layout.ts`. Os dois arquivos
 * precisam ser revisados juntos quando um layout mudar; o teste
 * `tests/sped-fields.test.ts` verifica que as posições usadas pelos parsers
 * estão descritas aqui.
 */

/** Como o valor deve ser apresentado e interpretado na tela de inspeção. */
export type SpedFieldType = 'TEXTO' | 'VALOR' | 'DATA' | 'QUANTIDADE' | 'ALIQUOTA' | 'CODIGO';

export interface SpedFieldSpec {
  /** Posição no layout: 1 é o próprio código do registro, 2 o primeiro campo. */
  readonly position: number;
  /** Nome oficial do campo, exatamente como no Guia Prático. */
  readonly name: string;
  /** Descrição do campo em português corrente. */
  readonly label: string;
  readonly type: SpedFieldType;
  /** Preenchido quando o parser atual não utiliza o campo. */
  readonly unused?: boolean;
}

export interface SpedRegisterSpec {
  readonly code: string;
  readonly description: string;
  readonly fields: readonly SpedFieldSpec[];
}

export type SpedCatalogue = ReadonlyMap<string, SpedRegisterSpec>;

function register(
  code: string,
  description: string,
  fields: readonly [number, string, string, SpedFieldType][],
): SpedRegisterSpec {
  return {
    code,
    description,
    fields: [
      { position: 1, name: 'REG', label: 'Código do registro', type: 'CODIGO' },
      ...fields.map(([position, name, label, type]) => ({ position, name, label, type })),
    ],
  };
}

function catalogue(entries: readonly SpedRegisterSpec[]): SpedCatalogue {
  return new Map(entries.map((entry) => [entry.code, entry]));
}

// ---------------------------------------------------------------------------
// EFD ICMS/IPI
// ---------------------------------------------------------------------------

export const EFD_ICMS_FIELDS: SpedCatalogue = catalogue([
  register('0000', 'Abertura do arquivo digital e identificação da entidade', [
    [2, 'COD_VER', 'Código da versão do leiaute', 'CODIGO'],
    [3, 'COD_FIN', 'Código da finalidade do arquivo', 'CODIGO'],
    [4, 'DT_INI', 'Data inicial das informações', 'DATA'],
    [5, 'DT_FIN', 'Data final das informações', 'DATA'],
    [6, 'NOME', 'Nome empresarial', 'TEXTO'],
    [7, 'CNPJ', 'CNPJ da entidade', 'TEXTO'],
    [8, 'CPF', 'CPF da entidade', 'TEXTO'],
    [9, 'UF', 'Sigla da unidade da federação', 'TEXTO'],
    [10, 'IE', 'Inscrição estadual', 'TEXTO'],
    [11, 'COD_MUN', 'Código do município (IBGE)', 'CODIGO'],
    [12, 'IM', 'Inscrição municipal', 'TEXTO'],
    [13, 'SUFRAMA', 'Inscrição na Suframa', 'TEXTO'],
    [14, 'IND_PERFIL', 'Perfil de apresentação do arquivo', 'CODIGO'],
    [15, 'IND_ATIV', 'Indicador de tipo de atividade', 'CODIGO'],
  ]),
  register('0005', 'Dados complementares da entidade', [
    [2, 'FANTASIA', 'Nome de fantasia', 'TEXTO'],
    [3, 'CEP', 'CEP', 'TEXTO'],
    [4, 'END', 'Logradouro', 'TEXTO'],
    [5, 'NUM', 'Número', 'TEXTO'],
    [6, 'COMPL', 'Complemento', 'TEXTO'],
    [7, 'BAIRRO', 'Bairro', 'TEXTO'],
    [8, 'FONE', 'Telefone', 'TEXTO'],
    [9, 'FAX', 'Fax', 'TEXTO'],
    [10, 'EMAIL', 'Endereço eletrônico', 'TEXTO'],
  ]),
  register('0100', 'Dados do contabilista', [
    [2, 'NOME', 'Nome do contabilista', 'TEXTO'],
    [3, 'CPF', 'CPF do contabilista', 'TEXTO'],
    [4, 'CRC', 'Número de inscrição no CRC', 'TEXTO'],
    [5, 'CNPJ', 'CNPJ do escritório de contabilidade', 'TEXTO'],
    [6, 'CEP', 'CEP', 'TEXTO'],
    [7, 'END', 'Logradouro', 'TEXTO'],
    [8, 'NUM', 'Número', 'TEXTO'],
    [9, 'COMPL', 'Complemento', 'TEXTO'],
    [10, 'BAIRRO', 'Bairro', 'TEXTO'],
    [11, 'FONE', 'Telefone', 'TEXTO'],
    [12, 'FAX', 'Fax', 'TEXTO'],
    [13, 'EMAIL', 'Endereço eletrônico', 'TEXTO'],
    [14, 'COD_MUN', 'Código do município (IBGE)', 'CODIGO'],
  ]),
  register('0150', 'Tabela de cadastro do participante', [
    [2, 'COD_PART', 'Código de identificação do participante', 'CODIGO'],
    [3, 'NOME', 'Nome do participante', 'TEXTO'],
    [4, 'COD_PAIS', 'Código do país', 'CODIGO'],
    [5, 'CNPJ', 'CNPJ do participante', 'TEXTO'],
    [6, 'CPF', 'CPF do participante', 'TEXTO'],
    [7, 'IE', 'Inscrição estadual do participante', 'TEXTO'],
    [8, 'COD_MUN', 'Código do município (IBGE)', 'CODIGO'],
    [9, 'SUFRAMA', 'Inscrição na Suframa', 'TEXTO'],
    [10, 'END', 'Logradouro', 'TEXTO'],
    [11, 'NUM', 'Número', 'TEXTO'],
    [12, 'COMPL', 'Complemento', 'TEXTO'],
    [13, 'BAIRRO', 'Bairro', 'TEXTO'],
  ]),
  register('0190', 'Identificação das unidades de medida', [
    [2, 'UNID', 'Código da unidade de medida', 'CODIGO'],
    [3, 'DESCR', 'Descrição da unidade de medida', 'TEXTO'],
  ]),
  register('0200', 'Tabela de identificação do item (produtos e serviços)', [
    [2, 'COD_ITEM', 'Código do item', 'CODIGO'],
    [3, 'DESCR_ITEM', 'Descrição do item', 'TEXTO'],
    [4, 'COD_BARRA', 'Código de barras', 'TEXTO'],
    [5, 'COD_ANT_ITEM', 'Código anterior do item', 'CODIGO'],
    [6, 'UNID_INV', 'Unidade de medida do inventário', 'CODIGO'],
    [7, 'TIPO_ITEM', 'Tipo do item', 'CODIGO'],
    [8, 'COD_NCM', 'Código NCM', 'CODIGO'],
    [9, 'EX_IPI', 'Código EX da TIPI', 'CODIGO'],
    [10, 'COD_GEN', 'Código do gênero do item', 'CODIGO'],
    [11, 'COD_LST', 'Código do serviço na lista da LC 116/2003', 'CODIGO'],
    [12, 'ALIQ_ICMS', 'Alíquota de ICMS aplicável ao item', 'ALIQUOTA'],
    [13, 'CEST', 'Código CEST', 'CODIGO'],
  ]),
  register('C100', 'Nota fiscal, nota fiscal avulsa, NF-e e NFC-e', [
    [2, 'IND_OPER', 'Indicador do tipo de operação (0 entrada, 1 saída)', 'CODIGO'],
    [3, 'IND_EMIT', 'Indicador do emitente (0 própria, 1 terceiros)', 'CODIGO'],
    [4, 'COD_PART', 'Código do participante', 'CODIGO'],
    [5, 'COD_MOD', 'Código do modelo do documento fiscal', 'CODIGO'],
    [6, 'COD_SIT', 'Código da situação do documento fiscal', 'CODIGO'],
    [7, 'SER', 'Série do documento fiscal', 'TEXTO'],
    [8, 'NUM_DOC', 'Número do documento fiscal', 'TEXTO'],
    [9, 'CHV_NFE', 'Chave da NF-e/NFC-e', 'TEXTO'],
    [10, 'DT_DOC', 'Data da emissão do documento fiscal', 'DATA'],
    [11, 'DT_E_S', 'Data da entrada ou da saída', 'DATA'],
    [12, 'VL_DOC', 'Valor total do documento fiscal', 'VALOR'],
    [13, 'IND_PGTO', 'Indicador do tipo de pagamento', 'CODIGO'],
    [14, 'VL_DESC', 'Valor total do desconto', 'VALOR'],
    [15, 'VL_ABAT_NT', 'Abatimento não tributado e não comercial', 'VALOR'],
    [16, 'VL_MERC', 'Valor total das mercadorias e serviços', 'VALOR'],
    [17, 'IND_FRT', 'Indicador do tipo do frete', 'CODIGO'],
    [18, 'VL_FRT', 'Valor do frete indicado no documento', 'VALOR'],
    [19, 'VL_SEG', 'Valor do seguro indicado no documento', 'VALOR'],
    [20, 'VL_OUT_DA', 'Valor de outras despesas acessórias', 'VALOR'],
    [21, 'VL_BC_ICMS', 'Valor da base de cálculo do ICMS', 'VALOR'],
    [22, 'VL_ICMS', 'Valor do ICMS', 'VALOR'],
    [23, 'VL_BC_ICMS_ST', 'Valor da base de cálculo do ICMS por substituição', 'VALOR'],
    [24, 'VL_ICMS_ST', 'Valor do ICMS retido por substituição tributária', 'VALOR'],
    [25, 'VL_IPI', 'Valor total do IPI', 'VALOR'],
    [26, 'VL_PIS', 'Valor total do PIS', 'VALOR'],
    [27, 'VL_COFINS', 'Valor total da COFINS', 'VALOR'],
    [28, 'VL_PIS_ST', 'Valor total do PIS retido por substituição', 'VALOR'],
    [29, 'VL_COFINS_ST', 'Valor total da COFINS retida por substituição', 'VALOR'],
  ]),
  register('C170', 'Itens do documento', [
    [2, 'NUM_ITEM', 'Número sequencial do item', 'CODIGO'],
    [3, 'COD_ITEM', 'Código do item', 'CODIGO'],
    [4, 'DESCR_COMPL', 'Descrição complementar do item', 'TEXTO'],
    [5, 'QTD', 'Quantidade do item', 'QUANTIDADE'],
    [6, 'UNID', 'Unidade do item', 'CODIGO'],
    [7, 'VL_ITEM', 'Valor total do item', 'VALOR'],
    [8, 'VL_DESC', 'Valor do desconto', 'VALOR'],
    [9, 'IND_MOV', 'Movimentação física do item', 'CODIGO'],
    [10, 'CST_ICMS', 'Código da situação tributária do ICMS', 'CODIGO'],
    [11, 'CFOP', 'Código fiscal de operação e prestação', 'CODIGO'],
    [12, 'COD_NAT', 'Código da natureza da operação', 'CODIGO'],
    [13, 'VL_BC_ICMS', 'Base de cálculo do ICMS', 'VALOR'],
    [14, 'ALIQ_ICMS', 'Alíquota do ICMS', 'ALIQUOTA'],
    [15, 'VL_ICMS', 'Valor do ICMS creditado/debitado', 'VALOR'],
    [16, 'VL_BC_ICMS_ST', 'Base de cálculo do ICMS por substituição', 'VALOR'],
    [17, 'ALIQ_ST', 'Alíquota do ICMS da substituição tributária', 'ALIQUOTA'],
    [18, 'VL_ICMS_ST', 'Valor do ICMS por substituição tributária', 'VALOR'],
    [19, 'IND_APUR', 'Indicador do período de apuração do IPI', 'CODIGO'],
    [20, 'CST_IPI', 'Código da situação tributária do IPI', 'CODIGO'],
    [21, 'COD_ENQ', 'Código de enquadramento legal do IPI', 'CODIGO'],
    [22, 'VL_BC_IPI', 'Base de cálculo do IPI', 'VALOR'],
    [23, 'ALIQ_IPI', 'Alíquota do IPI', 'ALIQUOTA'],
    [24, 'VL_IPI', 'Valor do IPI creditado/debitado', 'VALOR'],
    [25, 'CST_PIS', 'Código da situação tributária do PIS', 'CODIGO'],
    [26, 'VL_BC_PIS', 'Base de cálculo do PIS', 'VALOR'],
    [27, 'ALIQ_PIS', 'Alíquota do PIS (percentual)', 'ALIQUOTA'],
    [28, 'QUANT_BC_PIS', 'Quantidade base de cálculo do PIS', 'QUANTIDADE'],
    [29, 'ALIQ_PIS_QUANT', 'Alíquota do PIS (em reais)', 'ALIQUOTA'],
    [30, 'VL_PIS', 'Valor do PIS', 'VALOR'],
    [31, 'CST_COFINS', 'Código da situação tributária da COFINS', 'CODIGO'],
    [32, 'VL_BC_COFINS', 'Base de cálculo da COFINS', 'VALOR'],
    [33, 'ALIQ_COFINS', 'Alíquota da COFINS (percentual)', 'ALIQUOTA'],
    [34, 'QUANT_BC_COFINS', 'Quantidade base de cálculo da COFINS', 'QUANTIDADE'],
    [35, 'ALIQ_COFINS_QUANT', 'Alíquota da COFINS (em reais)', 'ALIQUOTA'],
    [36, 'VL_COFINS', 'Valor da COFINS', 'VALOR'],
    [37, 'COD_CTA', 'Código da conta analítica contábil', 'CODIGO'],
    [38, 'VL_ABAT_NT', 'Abatimento não tributado e não comercial', 'VALOR'],
  ]),
  register('C190', 'Registro analítico do documento', [
    [2, 'CST_ICMS', 'Código da situação tributária do ICMS', 'CODIGO'],
    [3, 'CFOP', 'Código fiscal de operação e prestação', 'CODIGO'],
    [4, 'ALIQ_ICMS', 'Alíquota do ICMS', 'ALIQUOTA'],
    [5, 'VL_OPR', 'Valor da operação na combinação CST/CFOP/alíquota', 'VALOR'],
    [6, 'VL_BC_ICMS', 'Base de cálculo do ICMS', 'VALOR'],
    [7, 'VL_ICMS', 'Valor do ICMS', 'VALOR'],
    [8, 'VL_BC_ICMS_ST', 'Base de cálculo do ICMS por substituição', 'VALOR'],
    [9, 'VL_ICMS_ST', 'Valor do ICMS por substituição tributária', 'VALOR'],
    [10, 'VL_RED_BC', 'Valor não tributado por redução da base de cálculo', 'VALOR'],
    [11, 'VL_IPI', 'Valor do IPI', 'VALOR'],
    [12, 'COD_OBS', 'Código da observação do lançamento fiscal', 'CODIGO'],
  ]),
  register('C195', 'Observações do lançamento fiscal', [
    [2, 'COD_OBS', 'Código da observação do lançamento fiscal', 'CODIGO'],
    [3, 'TXT_COMPL', 'Descrição complementar', 'TEXTO'],
  ]),
  register('C197', 'Outras obrigações tributárias, ajustes e informações', [
    [2, 'COD_AJ', 'Código do ajuste da apuração', 'CODIGO'],
    [3, 'DESCR_COMPL_AJ', 'Descrição complementar do ajuste', 'TEXTO'],
    [4, 'COD_ITEM', 'Código do item', 'CODIGO'],
    [5, 'VL_BC_ICMS', 'Base de cálculo do ICMS', 'VALOR'],
    [6, 'ALIQ_ICMS', 'Alíquota do ICMS', 'ALIQUOTA'],
    [7, 'VL_ICMS', 'Valor do ICMS', 'VALOR'],
    [8, 'VL_OUTROS', 'Outros valores', 'VALOR'],
  ]),
  register('E100', 'Período da apuração do ICMS', [
    [2, 'DT_INI', 'Data inicial a que a apuração se refere', 'DATA'],
    [3, 'DT_FIN', 'Data final a que a apuração se refere', 'DATA'],
  ]),
  register('E110', 'Apuração do ICMS — operações próprias', [
    [2, 'VL_TOT_DEBITOS', 'Valor total dos débitos por saídas e prestações', 'VALOR'],
    [3, 'VL_AJ_DEBITOS', 'Valor total dos ajustes a débito', 'VALOR'],
    [4, 'VL_TOT_AJ_DEBITOS', 'Valor total dos ajustes a débito por documento', 'VALOR'],
    [5, 'VL_ESTORNOS_CRED', 'Valor total dos estornos de créditos', 'VALOR'],
    [6, 'VL_TOT_CREDITOS', 'Valor total dos créditos por entradas e aquisições', 'VALOR'],
    [7, 'VL_AJ_CREDITOS', 'Valor total dos ajustes a crédito', 'VALOR'],
    [8, 'VL_TOT_AJ_CREDITOS', 'Valor total dos ajustes a crédito por documento', 'VALOR'],
    [9, 'VL_ESTORNOS_DEB', 'Valor total dos estornos de débitos', 'VALOR'],
    [10, 'VL_SLD_CREDOR_ANT', 'Saldo credor do período anterior', 'VALOR'],
    [11, 'VL_SLD_APURADO', 'Saldo devedor apurado', 'VALOR'],
    [12, 'VL_TOT_DED', 'Valor total das deduções', 'VALOR'],
    [13, 'VL_ICMS_RECOLHER', 'Valor do ICMS a recolher', 'VALOR'],
    [14, 'VL_SLD_CREDOR_TRANSPORTAR', 'Saldo credor a transportar para o período seguinte', 'VALOR'],
    [15, 'DEB_ESP', 'Débitos especiais', 'VALOR'],
  ]),
  register('E111', 'Ajuste, benefício ou incentivo da apuração do ICMS', [
    [2, 'COD_AJ_APUR', 'Código do ajuste da apuração', 'CODIGO'],
    [3, 'DESCR_COMPL_AJ', 'Descrição complementar do ajuste', 'TEXTO'],
    [4, 'VL_AJ_APUR', 'Valor do ajuste da apuração', 'VALOR'],
  ]),
]);

// ---------------------------------------------------------------------------
// EFD-Contribuições
// ---------------------------------------------------------------------------

export const EFD_CONTRIB_FIELDS: SpedCatalogue = catalogue([
  register('0000', 'Abertura do arquivo digital e identificação da pessoa jurídica', [
    [2, 'COD_VER', 'Código da versão do leiaute', 'CODIGO'],
    [3, 'TIPO_ESCRIT', 'Tipo de escrituração', 'CODIGO'],
    [4, 'IND_SIT_ESP', 'Indicador de situação especial', 'CODIGO'],
    [5, 'NUM_REC_ANTERIOR', 'Número do recibo da escrituração anterior', 'TEXTO'],
    [6, 'DT_INI', 'Data inicial das informações', 'DATA'],
    [7, 'DT_FIN', 'Data final das informações', 'DATA'],
    [8, 'NOME', 'Nome empresarial', 'TEXTO'],
    [9, 'CNPJ', 'CNPJ da pessoa jurídica', 'TEXTO'],
    [10, 'UF', 'Sigla da unidade da federação', 'TEXTO'],
    [11, 'COD_MUN', 'Código do município (IBGE)', 'CODIGO'],
    [12, 'SUFRAMA', 'Inscrição na Suframa', 'TEXTO'],
    [13, 'IND_NAT_PJ', 'Indicador da natureza da pessoa jurídica', 'CODIGO'],
    [14, 'IND_ATIV', 'Indicador do tipo de atividade preponderante', 'CODIGO'],
  ]),
  register('0110', 'Regimes de apuração da contribuição social e de apropriação de crédito', [
    [2, 'COD_INC_TRIB', 'Código do indicador da incidência tributária', 'CODIGO'],
    [3, 'IND_APRO_CRED', 'Indicador do método de apropriação de créditos', 'CODIGO'],
    [4, 'COD_TIPO_CONT', 'Código do tipo de contribuição apurada', 'CODIGO'],
    [5, 'IND_REG_CUM', 'Indicador do critério de escrituração do regime cumulativo', 'CODIGO'],
  ]),
  register('0140', 'Tabela de cadastro de estabelecimento', [
    [2, 'COD_EST', 'Código do estabelecimento', 'CODIGO'],
    [3, 'NOME', 'Nome empresarial do estabelecimento', 'TEXTO'],
    [4, 'CNPJ', 'CNPJ do estabelecimento', 'TEXTO'],
    [5, 'UF', 'Sigla da unidade da federação', 'TEXTO'],
    [6, 'IE', 'Inscrição estadual', 'TEXTO'],
    [7, 'COD_MUN', 'Código do município (IBGE)', 'CODIGO'],
    [8, 'IM', 'Inscrição municipal', 'TEXTO'],
    [9, 'SUFRAMA', 'Inscrição na Suframa', 'TEXTO'],
  ]),
  register('0150', 'Tabela de cadastro do participante', [
    [2, 'COD_PART', 'Código de identificação do participante', 'CODIGO'],
    [3, 'NOME', 'Nome do participante', 'TEXTO'],
    [4, 'COD_PAIS', 'Código do país', 'CODIGO'],
    [5, 'CNPJ', 'CNPJ do participante', 'TEXTO'],
    [6, 'CPF', 'CPF do participante', 'TEXTO'],
    [7, 'IE', 'Inscrição estadual do participante', 'TEXTO'],
    [8, 'COD_MUN', 'Código do município (IBGE)', 'CODIGO'],
    [9, 'SUFRAMA', 'Inscrição na Suframa', 'TEXTO'],
    [10, 'END', 'Logradouro', 'TEXTO'],
    [11, 'NUM', 'Número', 'TEXTO'],
    [12, 'COMPL', 'Complemento', 'TEXTO'],
    [13, 'BAIRRO', 'Bairro', 'TEXTO'],
  ]),
  register('0200', 'Tabela de identificação do item', [
    [2, 'COD_ITEM', 'Código do item', 'CODIGO'],
    [3, 'DESCR_ITEM', 'Descrição do item', 'TEXTO'],
    [4, 'COD_BARRA', 'Código de barras', 'TEXTO'],
    [5, 'COD_ANT_ITEM', 'Código anterior do item', 'CODIGO'],
    [6, 'UNID_INV', 'Unidade de medida do inventário', 'CODIGO'],
    [7, 'TIPO_ITEM', 'Tipo do item', 'CODIGO'],
    [8, 'COD_NCM', 'Código NCM', 'CODIGO'],
    [9, 'EX_IPI', 'Código EX da TIPI', 'CODIGO'],
    [10, 'COD_GEN', 'Código do gênero do item', 'CODIGO'],
    [11, 'COD_LST', 'Código do serviço na lista da LC 116/2003', 'CODIGO'],
    [12, 'ALIQ_ICMS', 'Alíquota de ICMS aplicável ao item', 'ALIQUOTA'],
    [13, 'CEST', 'Código CEST', 'CODIGO'],
  ]),
  register('A100', 'Documento — nota fiscal de serviço', [
    [2, 'IND_OPER', 'Indicador do tipo de operação (0 aquisição, 1 prestação)', 'CODIGO'],
    [3, 'IND_EMIT', 'Indicador do emitente (0 própria, 1 terceiros)', 'CODIGO'],
    [4, 'COD_PART', 'Código do participante', 'CODIGO'],
    [5, 'COD_SIT', 'Código da situação do documento fiscal', 'CODIGO'],
    [6, 'SER', 'Série do documento fiscal', 'TEXTO'],
    [7, 'SUB', 'Subsérie do documento fiscal', 'TEXTO'],
    [8, 'NUM_DOC', 'Número do documento fiscal', 'TEXTO'],
    [9, 'CHV_NFSE', 'Chave da NFS-e', 'TEXTO'],
    [10, 'DT_DOC', 'Data da emissão do documento fiscal', 'DATA'],
    [11, 'DT_EXE_SERV', 'Data da execução do serviço', 'DATA'],
    [12, 'VL_DOC', 'Valor total do documento', 'VALOR'],
    [13, 'IND_PGTO', 'Indicador do tipo de pagamento', 'CODIGO'],
    [14, 'VL_DESC', 'Valor total do desconto', 'VALOR'],
    [15, 'VL_BC_PIS', 'Valor da base de cálculo do PIS/Pasep', 'VALOR'],
    [16, 'VL_PIS', 'Valor do PIS/Pasep', 'VALOR'],
    [17, 'VL_BC_COFINS', 'Valor da base de cálculo da COFINS', 'VALOR'],
    [18, 'VL_COFINS', 'Valor da COFINS', 'VALOR'],
    [19, 'VL_PIS_RET', 'Valor do PIS/Pasep retido na fonte', 'VALOR'],
    [20, 'VL_COFINS_RET', 'Valor da COFINS retida na fonte', 'VALOR'],
    [21, 'VL_ISS', 'Valor do ISS', 'VALOR'],
  ]),
  register('C100', 'Documento — nota fiscal, NF-e e NFC-e', [
    [2, 'IND_OPER', 'Indicador do tipo de operação (0 entrada, 1 saída)', 'CODIGO'],
    [3, 'IND_EMIT', 'Indicador do emitente (0 própria, 1 terceiros)', 'CODIGO'],
    [4, 'COD_PART', 'Código do participante', 'CODIGO'],
    [5, 'COD_MOD', 'Código do modelo do documento fiscal', 'CODIGO'],
    [6, 'COD_SIT', 'Código da situação do documento fiscal', 'CODIGO'],
    [7, 'SER', 'Série do documento fiscal', 'TEXTO'],
    [8, 'NUM_DOC', 'Número do documento fiscal', 'TEXTO'],
    [9, 'CHV_NFE', 'Chave da NF-e/NFC-e', 'TEXTO'],
    [10, 'DT_DOC', 'Data da emissão do documento fiscal', 'DATA'],
    [11, 'DT_E_S', 'Data da entrada ou da saída', 'DATA'],
    [12, 'VL_DOC', 'Valor total do documento fiscal', 'VALOR'],
    [13, 'IND_PGTO', 'Indicador do tipo de pagamento', 'CODIGO'],
    [14, 'VL_DESC', 'Valor total do desconto', 'VALOR'],
    [15, 'VL_ABAT_NT', 'Abatimento não tributado e não comercial', 'VALOR'],
    [16, 'VL_MERC', 'Valor total das mercadorias e serviços', 'VALOR'],
    [17, 'IND_FRT', 'Indicador do tipo do frete', 'CODIGO'],
    [18, 'VL_FRT', 'Valor do frete indicado no documento', 'VALOR'],
    [19, 'VL_SEG', 'Valor do seguro indicado no documento', 'VALOR'],
    [20, 'VL_OUT_DA', 'Valor de outras despesas acessórias', 'VALOR'],
    [21, 'VL_BC_ICMS', 'Valor da base de cálculo do ICMS', 'VALOR'],
    [22, 'VL_ICMS', 'Valor do ICMS', 'VALOR'],
    [23, 'VL_BC_ICMS_ST', 'Valor da base de cálculo do ICMS por substituição', 'VALOR'],
    [24, 'VL_ICMS_ST', 'Valor do ICMS retido por substituição tributária', 'VALOR'],
    [25, 'VL_IPI', 'Valor total do IPI', 'VALOR'],
    [26, 'VL_PIS', 'Valor total do PIS/Pasep', 'VALOR'],
    [27, 'VL_COFINS', 'Valor total da COFINS', 'VALOR'],
    [28, 'VL_PIS_ST', 'Valor total do PIS/Pasep retido por substituição', 'VALOR'],
    [29, 'VL_COFINS_ST', 'Valor total da COFINS retida por substituição', 'VALOR'],
  ]),
  register('C170', 'Complemento do documento — itens', [
    [2, 'NUM_ITEM', 'Número sequencial do item', 'CODIGO'],
    [3, 'COD_ITEM', 'Código do item', 'CODIGO'],
    [4, 'DESCR_COMPL', 'Descrição complementar do item', 'TEXTO'],
    [5, 'QTD', 'Quantidade do item', 'QUANTIDADE'],
    [6, 'UNID', 'Unidade do item', 'CODIGO'],
    [7, 'VL_ITEM', 'Valor total do item', 'VALOR'],
    [8, 'VL_DESC', 'Valor do desconto', 'VALOR'],
    [9, 'IND_MOV', 'Movimentação física do item', 'CODIGO'],
    [10, 'CST_ICMS', 'Código da situação tributária do ICMS', 'CODIGO'],
    [11, 'CFOP', 'Código fiscal de operação e prestação', 'CODIGO'],
    [12, 'COD_NAT', 'Código da natureza da operação', 'CODIGO'],
    [13, 'VL_BC_ICMS', 'Base de cálculo do ICMS', 'VALOR'],
    [14, 'ALIQ_ICMS', 'Alíquota do ICMS', 'ALIQUOTA'],
    [15, 'VL_ICMS', 'Valor do ICMS', 'VALOR'],
    [16, 'VL_BC_ICMS_ST', 'Base de cálculo do ICMS por substituição', 'VALOR'],
    [17, 'ALIQ_ST', 'Alíquota do ICMS da substituição tributária', 'ALIQUOTA'],
    [18, 'VL_ICMS_ST', 'Valor do ICMS por substituição tributária', 'VALOR'],
    [19, 'IND_APUR', 'Indicador do período de apuração do IPI', 'CODIGO'],
    [20, 'CST_IPI', 'Código da situação tributária do IPI', 'CODIGO'],
    [21, 'COD_ENQ', 'Código de enquadramento legal do IPI', 'CODIGO'],
    [22, 'VL_BC_IPI', 'Base de cálculo do IPI', 'VALOR'],
    [23, 'ALIQ_IPI', 'Alíquota do IPI', 'ALIQUOTA'],
    [24, 'VL_IPI', 'Valor do IPI', 'VALOR'],
    [25, 'CST_PIS', 'Código da situação tributária do PIS/Pasep', 'CODIGO'],
    [26, 'VL_BC_PIS', 'Base de cálculo do PIS/Pasep', 'VALOR'],
    [27, 'ALIQ_PIS', 'Alíquota do PIS/Pasep (percentual)', 'ALIQUOTA'],
    [28, 'QUANT_BC_PIS', 'Quantidade base de cálculo do PIS/Pasep', 'QUANTIDADE'],
    [29, 'ALIQ_PIS_QUANT', 'Alíquota do PIS/Pasep (em reais)', 'ALIQUOTA'],
    [30, 'VL_PIS', 'Valor do PIS/Pasep', 'VALOR'],
    [31, 'CST_COFINS', 'Código da situação tributária da COFINS', 'CODIGO'],
    [32, 'VL_BC_COFINS', 'Base de cálculo da COFINS', 'VALOR'],
    [33, 'ALIQ_COFINS', 'Alíquota da COFINS (percentual)', 'ALIQUOTA'],
    [34, 'QUANT_BC_COFINS', 'Quantidade base de cálculo da COFINS', 'QUANTIDADE'],
    [35, 'ALIQ_COFINS_QUANT', 'Alíquota da COFINS (em reais)', 'ALIQUOTA'],
    [36, 'VL_COFINS', 'Valor da COFINS', 'VALOR'],
    [37, 'COD_CTA', 'Código da conta analítica contábil', 'CODIGO'],
    [38, 'VL_ABAT_NT', 'Abatimento não tributado e não comercial', 'VALOR'],
  ]),
  register('C175', 'Registro analítico do documento', [
    [2, 'CFOP', 'Código fiscal de operação e prestação', 'CODIGO'],
    [3, 'VL_OPR', 'Valor da operação', 'VALOR'],
    [4, 'VL_DESC', 'Valor do desconto', 'VALOR'],
    [5, 'CST_PIS', 'Código da situação tributária do PIS/Pasep', 'CODIGO'],
    [6, 'VL_BC_PIS', 'Base de cálculo do PIS/Pasep', 'VALOR'],
    [7, 'ALIQ_PIS', 'Alíquota do PIS/Pasep', 'ALIQUOTA'],
    [8, 'VL_PIS', 'Valor do PIS/Pasep', 'VALOR'],
    [9, 'CST_COFINS', 'Código da situação tributária da COFINS', 'CODIGO'],
    [10, 'VL_BC_COFINS', 'Base de cálculo da COFINS', 'VALOR'],
    [11, 'ALIQ_COFINS', 'Alíquota da COFINS', 'ALIQUOTA'],
    [12, 'VL_COFINS', 'Valor da COFINS', 'VALOR'],
    [13, 'COD_CTA', 'Código da conta analítica contábil', 'CODIGO'],
    [14, 'INFO_COMPL', 'Informação complementar', 'TEXTO'],
  ]),
  register('F100', 'Demais documentos e operações geradoras de contribuição e crédito', [
    [2, 'IND_OPER', 'Indicador do tipo de operação', 'CODIGO'],
    [3, 'COD_PART', 'Código do participante', 'CODIGO'],
    [4, 'COD_ITEM', 'Código do item', 'CODIGO'],
    [5, 'DT_OPER', 'Data da operação', 'DATA'],
    [6, 'VL_OPER', 'Valor da operação', 'VALOR'],
    [7, 'CST_PIS', 'Código da situação tributária do PIS/Pasep', 'CODIGO'],
    [8, 'VL_BC_PIS', 'Base de cálculo do PIS/Pasep', 'VALOR'],
    [9, 'ALIQ_PIS', 'Alíquota do PIS/Pasep', 'ALIQUOTA'],
    [10, 'VL_PIS', 'Valor do PIS/Pasep', 'VALOR'],
    [11, 'CST_COFINS', 'Código da situação tributária da COFINS', 'CODIGO'],
    [12, 'VL_BC_COFINS', 'Base de cálculo da COFINS', 'VALOR'],
    [13, 'ALIQ_COFINS', 'Alíquota da COFINS', 'ALIQUOTA'],
    [14, 'VL_COFINS', 'Valor da COFINS', 'VALOR'],
    [15, 'NAT_BC_CRED', 'Código da base de cálculo do crédito', 'CODIGO'],
    [16, 'IND_ORIG_CRED', 'Indicador da origem do crédito', 'CODIGO'],
    [17, 'COD_CTA', 'Código da conta analítica contábil', 'CODIGO'],
    [18, 'COD_CCUS', 'Código do centro de custos', 'CODIGO'],
    [19, 'DESC_DOC_OPER', 'Descrição do documento ou da operação', 'TEXTO'],
  ]),
  register('M200', 'Consolidação da contribuição para o PIS/Pasep do período', [
    [2, 'VL_TOT_CONT_NC_PER', 'Contribuição não cumulativa apurada no período', 'VALOR'],
    [3, 'VL_TOT_CRED_DESC', 'Créditos descontados no período', 'VALOR'],
    [4, 'VL_TOT_CRED_DESC_ANT', 'Créditos de períodos anteriores descontados', 'VALOR'],
    [5, 'VL_TOT_CONT_NC_DEV', 'Contribuição não cumulativa devida', 'VALOR'],
    [6, 'VL_RET_NC', 'Retenções na fonte no regime não cumulativo', 'VALOR'],
    [7, 'VL_OUT_DED_NC', 'Outras deduções no regime não cumulativo', 'VALOR'],
    [8, 'VL_CONT_NC_REC', 'Contribuição não cumulativa a recolher', 'VALOR'],
    [9, 'VL_TOT_CONT_CUM_PER', 'Contribuição cumulativa apurada no período', 'VALOR'],
    [10, 'VL_RET_CUM', 'Retenções na fonte no regime cumulativo', 'VALOR'],
    [11, 'VL_OUT_DED_CUM', 'Outras deduções no regime cumulativo', 'VALOR'],
    [12, 'VL_CONT_CUM_REC', 'Contribuição cumulativa a recolher', 'VALOR'],
    [13, 'VL_TOT_CONT_REC', 'Total da contribuição a recolher no período', 'VALOR'],
  ]),
  register('M600', 'Consolidação da COFINS do período', [
    [2, 'VL_TOT_CONT_NC_PER', 'Contribuição não cumulativa apurada no período', 'VALOR'],
    [3, 'VL_TOT_CRED_DESC', 'Créditos descontados no período', 'VALOR'],
    [4, 'VL_TOT_CRED_DESC_ANT', 'Créditos de períodos anteriores descontados', 'VALOR'],
    [5, 'VL_TOT_CONT_NC_DEV', 'Contribuição não cumulativa devida', 'VALOR'],
    [6, 'VL_RET_NC', 'Retenções na fonte no regime não cumulativo', 'VALOR'],
    [7, 'VL_OUT_DED_NC', 'Outras deduções no regime não cumulativo', 'VALOR'],
    [8, 'VL_CONT_NC_REC', 'Contribuição não cumulativa a recolher', 'VALOR'],
    [9, 'VL_TOT_CONT_CUM_PER', 'Contribuição cumulativa apurada no período', 'VALOR'],
    [10, 'VL_RET_CUM', 'Retenções na fonte no regime cumulativo', 'VALOR'],
    [11, 'VL_OUT_DED_CUM', 'Outras deduções no regime cumulativo', 'VALOR'],
    [12, 'VL_CONT_CUM_REC', 'Contribuição cumulativa a recolher', 'VALOR'],
    [13, 'VL_TOT_CONT_REC', 'Total da contribuição a recolher no período', 'VALOR'],
  ]),
]);

export function catalogueFor(source: 'EFD_ICMS_IPI' | 'EFD_CONTRIBUICOES'): SpedCatalogue {
  return source === 'EFD_ICMS_IPI' ? EFD_ICMS_FIELDS : EFD_CONTRIB_FIELDS;
}
